baseURL = "https://hmaier-dev.github.io/wiki/"
# baseURL = "http://localhost:1313/wiki/"
languageCode = "de-de"
title = "Wiki"
enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

## Needed for css.TailwindCSS
[[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[taxonomies]
  category = 'categories'

[markup]
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2

[outputFormats]
  [outputFormats.Search]
  mediaType = 'application/json'
  baseName = 'search'
  isPlainText = true

[outputs]
home = ['html','Search']

