baseURL = "https://hmaier-dev.github.io/wiki/"
# baseURL = "http://localhost:1313/wiki/"
languageCode = "de-de"
title = "Wiki"
disablePathToLower = true

## Needed for css.TailwindCSS
[[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[taxonomies]
  category = 'categories'
