---

name: Earthly +publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - content/**
      - layouts/**
      - assets/**
jobs:
  publish:
    runs-on: ubuntu-24.04
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      EARTHLY_VERSION: v0.8.13
      EARTHLY_PATH: /opt/earthly/v0.8.13
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Setup cache for earthly binary
      id: earthly-binary
      uses: actions/cache@v4
      with:
        path: /opt/earthly/v0.8.13
        # If version changes, a new binary will be downloaded
        key: earthly-${{ runner.os }}-${{ env.EARTHLY_VERSION }}

    - name: Download Binary if Not Cached
      if: steps.earthly-binary.outputs.cache-hit != 'true'
      run: |
        mkdir -p "$EARTHLY_PATH"
        curl -L -o "$EARTHLY_PATH"/earthly https://github.com/earthly/earthly/releases/download/$EARTHLY_VERSION/earthly-linux-amd64
        chmod +x $EARTHLY_PATH/earthly

    - name: Add earthly to PATH
      run: echo "$EARTHLY_PATH" >> $GITHUB_PATH

    - name: Check if earthly is in path
      run: earthly --version

    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"

    - name: Cache Docker images for earthly
      id: docker-cache
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('Earthfile') }}

    - name: Pull image if not cached
      if: steps.docker-cache.outputs.cache-hit != 'true'
      run: |
          docker pull hmaierdev/hugo-plus-tailwind:latest

    - name: Earthly +build
      run: |
        earthly +build

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        # you don't need to create this token. It is created by the runner itself
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        force_orphan: true
