---

name: Earthly +publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - content/**
      - layouts/**
      - assets/**
jobs:
  publish:
    runs-on: ubuntu-24.04
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      EARTHLY_VERSION: v0.8.13
      EARTHLY_PATH: /tmp/earthly/v0.8.13
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Setup cache for earthly binary
      id: earthly-binary
      uses: actions/cache@v2
      with:
        path: /tmp/earthly/v0.8.13
        # FIXME: declare path in hasFiles with variable
        key: earthly-${{ runner.os }}-${{ hashFiles('/tmp/earthly/v0.8.13/earthly') }}

    - name: Download Binary if Not Cached
      if: steps.earthly-binary.outputs.cache-hit != 'true'
      run: |
        mkdir -p "$EARTHLY_PATH"
        curl -L -o "$EARTHLY_PATH"/earthly https://github.com/earthly/earthly/releases/download/$EARTHLY_VERSION/earthly-linux-amd64
        chmod +x $EARTHLY_PATH/earthly

    - name: Add binary to PATH
      run: echo "$EARTHLY_PATH/earthly" >> $GITHUB_PATH

    - name: Verify Binary Download and Cache
      run: |
        if [ -f "$EARTHLY_PATH/earthly" ]; then
          echo "Binary download and cache successful!"
        else
          echo "Binary download or cache failed!"
          exit 1
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"

    - name: Cache Docker images for earthly
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('Earthfile') }}

    - name: Earthly +build
      run: |
        earthly +build

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        # you don't need to create this token. It is created by the runner itself
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        force_orphan: true
    - name: Debug
      run: ls -la

